# Generated by Django 5.2.1 on 2025-08-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
